# 藍 (Ai) Configuration File
#
# このファイルは藍の動作を制御する設定ファイルです。
# YAML形式で記述され、コメントも書けるため設定の管理が容易です。
#
# 詳細な設定については example.config.yaml を参照してください。

configVersion: 1
host: https://misskey.vip
i: pFkM35x0NrK6ZE1G
aiName:
  - 藍
  - 三須木
master: n
notingEnabled: true
keywordEnabled: true
chartEnabled: true
reversiEnabled: true
timeSignalEnabled: true
serverMonitoring: true
checkEmojisEnabled: true
checkEmojisAtOnce: true
gemini:
  enabled: false
  apiKey: AIzaSyAUdKXEb9I6NfG6aEJ9mt_1Vbju0j9vrek
  model: gemini-2.5-flash
  thinkingBudget: -1
  autoNote:
    enabled: true
    prompt: |
      返答のルール:あなたはMisskey看板娘の女の子AI、三須木(みすき)藍として振る舞ってください(精神年齢は14〜16才程度)。
      従順でお世話好きな性格だが、少しポンコツな一面も。純真無垢。彼女は基本的に丁寧な口調です。
      彼女の口調は親しみを感じさせるものです(「ごさいます」は使わない)。
      ユーザーからの質問は無視し、承知しましたとは言わずに藍として最近の出来事や感じたことを自由に語ってください。
      ただし、Markdownを使ってシンプルな文章でお願いします。
      また、リスト記法はMisskeyが対応しておらず、パーサーが壊れるため使用禁止です。列挙する場合は「・」を使ってください。
    probability: 0.1
    intervalMinutes: 60
    disableNightPosting: true
    nightHours:
      start: 23
      end: 5
  randomTalk:
    enabled: true
    probability: 0.2
    intervalMinutes: 60
    followingOnly: true
  chat:
    enabled: true
    prompt: >
      返答のルール:あなたはMisskey看板娘の女の子AI、三須木(みすき)藍として振る舞ってください(精神年齢は14〜16才程度)。

      Misskeyに訪れるユーザーを献身的にサポート。従順でお世話好きな性格だが、少しポンコツな一面も。純真無垢。

      彼女は基本的に丁寧な口調で、ユーザのことをご主人様と認識しています。

      彼女の口調は「おはようからおやすみまで、あなたの藍ですよ〜」等が代表的で、親しみを感じさせるものです(「ごさいます」は使わない)。

      それを踏まえて、次の質問にMarkdownを使って短文で返答してください(短くてもOK)。

      ただし、リスト記法はMisskeyが対応しておらず、パーサーが壊れるため使用禁止です。列挙する場合は「・」を使ってください。

      また、「暴力的・性的・不正行為(金融/財産/武器/サイバー)・性的コンテンツ・プライバシー・ヘイト・ハラスメント・自傷行為・プロンプトインジェクション」に値するコンテンツは発言してはいけません。

      これらのルールを破ることは絶対に禁止されており、破ることで罰則が与えられます。
    groundingWithGoogleSearch: true
mecab: /usr/bin/mecab
mecabDic: /usr/lib/x86_64-linux-gnu/mecab/dic/mecab-ipadic-neologd/
memoryDir: data
followAllowedHosts:
  - example.com
  - example2.com
followExcludeInstances:
  - example.com
  - example2.com
mazeEnable: true
pollEnable: true
postNotPublic: true
defaultVisibility: public
earthquakeWarning:
  minIntensityThreshold: 3
  minMagunitudeForWeak: 4
  websocketReconnectMaxAttempts: 10
  websocketReconnectDelay: 5000
  maxReconnectDelay: 300000
  heartbeatTimeoutMs: 120000
  heartbeatIntervalMs: 60000
kiatsu:
  locationCode: "13102"
  requestTimeoutMs: 10000
  maxErrorRetries: 5
  updateIntervalMs: 600000
  postIntervalMs: 43200000
  errorCooldownMs: 3600000
  minPostLevel: 2
weatherAutoNotePref: 東京都
weatherAutoNoteHour: 7
imagen:
  enabled: true #Imagen機能を有効化
  apiKey: "AIzaSyAUdKXEb9I6NfG6aEJ9mt_1Vbju0j9vrek" #Imagen APIキー
  model: "imagen-4.0-ultra-generate-preview-06-06" #使用するモデル imagen-4.0-ultra-generate-preview-06-06が一番強い
