# serifs.toml サンプル設定
# このファイルは、serifs.toml の設定例です。
# 各セクションでメッセージや機能を上書き・追加できます。
# core: セクションでは、基本的なメッセージの上書き例を示します。
# keyword: セクションでは、新しいセクションの追加例を示します。
# 必要に応じて、他のセクションも追加できます。
# {name} のように渡される変数をセリフで使用できます。(詳細は serifs.ts を参照)

[core]
setNameOk = "了解しました！これから新しい名前でお呼びします。{name}！"
san = "さん、付けましょうか？"
yesOrNo = "「はい」または「いいえ」でお答えください"
hello = "こんにちは、特別仕様です♪"

[core.erait.general]
# 配列形式
values = [
  "あなた、今日もえらいです！",
  "素晴らしいですね！"
]

[core.erait.specify.work]
# 配列形式
values = [
  "お疲れ様です、頑張ってますね！"
]

[keyword]
learned = "（{word}、{reading} を覚えました）"

[noting]
notes = [
  "元のメモ1",
  "元のメモ2"
]
